configuration: Release

install:
  - ps: Install-Product node "Stable"
  - npm install -g npm
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
  
before_build:
  - nuget restore
  - cd src/Sofia.WebApp/
  - npm install

build:
 
  publish_wap: true   
  verbosity: normal

notifications:

  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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

