configuration: Release

install:
  - ps: Install-Product node "Stable"
  - npm install -g npm
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
     
before_build:
  - cd SofiaWebApi
  - nuget restore
  - cd ..
  - cd SofiaWebApp
  - npm install
  - cd ..
  - cd ..

build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"cwi-projeto-sofia" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=2b68ae5b5cd4b5113db54dc2886ddca14662e87a"
  - msbuild "SofiaWebApi/SofiaWebApi.sln"
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=2b68ae5b5cd4b5113db54dc2886ddca14662e87a"
build:
 
  publish_wap: true   
  verbosity: normal

notifications:

  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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

